message("Project Name: " ${PROJECT_NAME})
message("CMake Project Name: " ${CMAKE_PROJECT_NAME})
message("Project Source Dir: " ${PROJECT_SOURCE_DIR})
message("Project Binary Dir: " ${PROJECT_BINARY_DIR})
message("Hello Source Dir: " ${Hello_SOURCE_DIR})
message("Hello Binary Dir: " ${Hello_BINARY_DIR})
message("Project Version: " ${PROJECT_VERSION})
message("CMake Project Version: " ${CMAKE_PROJECT_VERSION})
message("Project Version Major: " ${PROJECT_VERSION_MAJOR})
message("Project Version Minor: " ${PROJECT_VERSION_MINOR})
message("Project Version Patch: " ${PROJECT_VERSION_PATCH})
message("Project Version Tweak: " ${PROJECT_VERSION_TWEAK})
message("Project Description: " ${PROJECT_DESCRIPTION})
message("Project Homepage: " ${PROJECT_HOMEPAGE_URL})
